
IMAGE_NAME="ubuntu/xenial64"
NODES=2

Vagrant.configure("2") do |config|

  config.vm.box = IMAGE_NAME

  config.vm.provider "virtualbox" do |vb|
    vb.memory  = 1024
    vb.cpus    = 2
  end


  config.vm.define "master", primary: true do |master|

    master.vm.hostname = "master.kubernetes.vm"
    master.vm.network "private_network", ip: "192.168.50.100"
    master.vm.network "forwarded_port", guest: 6443, host: 6443
    master.vm.network "forwarded_port", guest: 8001, host: 8001

  end

  (1..NODES).each do |i|

    ip = 100 + i

    config.vm.define "worker#{i}", primary: true do |worker|

      worker.vm.hostname = "worker#{i}.kubernetes.vm"
      worker.vm.network "private_network", ip: "192.168.50.#{ip}"

    end

  end

end


